sudo: required
services:
  - docker

language: clojure
lein: 2.9.1
jdk:
  - oraclejdk8

cache:
  directories:
    - ${HOME}/.m2
    - ${HOME}/.lein

stages:
  - setup
  - test
  - deploy

jobs:
  include:
    - stage: setup
      name: Prepare cache
      script: lein -U deps

    - stage: test
      name: Cloverage
      script: lein cloverage

    - stage: test
      name: Test
      script: lein test

    - stage: deploy
      name: Push to DockerHub
      script: .travis/build-docker
      if: type = push
