# based on the example YAML
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein test

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
              docker build -t magthe/ci-test-clj:${CIRCLE_BRANCH} .
              docker tag magthe/ci-test-clj:${CIRCLE_BRANCH} magthe/ci-test-clj:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWD}
              docker push magthe/ci-test-clj
