#! /bin/bash

set -euo pipefail

lein uberjar

docker build -t magthe/ci-test-clj:travis-${TRAVIS_BRANCH} .
docker tag magthe/ci-test-clj:travis-${TRAVIS_BRANCH} \
       magthe/ci-test-clj:travis-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}

echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin
docker push magthe/ci-test-clj
